# Generated by Django 3.0.5 on 2021-05-02 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email_id', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=30)),
                ('profile', models.ImageField(upload_to='')),
            ],
        ),
    ]
