# Generated by Django 3.0.5 on 2021-05-02 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PG', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
