# Generated by Django 3.0.5 on 2021-05-04 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PG', '0003_properties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='Image1',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='properties',
            name='Image10',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='properties',
            name='Image2',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='properties',
            name='Image3',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='properties',
            name='Image4',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='properties',
            name='Image5',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='properties',
            name='Image6',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='properties',
            name='Image7',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='properties',
            name='Image8',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='properties',
            name='Image9',
            field=models.FileField(upload_to=''),
        ),
    ]
